/**
 * Email Module — reusable SMTP email sender for Plumtek backend
 */
import nodemailer from "nodemailer";

const config = {
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT ?? 587),
  secure: process.env.SMTP_SECURE === "true",
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
};

const from = process.env.EMAIL_FROM || config.auth.user || "no-reply@plumtek.com";
const hrEmail = process.env.HR_EMAIL || process.env.SITE_EMAIL || "hr@plumtek.com";

let transporter = null;
function getTransporter() {
  if (transporter) return transporter;
  if (!config.host || !config.auth.user || !config.auth.pass) {
    console.warn("[email] SMTP not configured - email sending disabled.");
    return null;
  }
  transporter = nodemailer.createTransport(config);
  return transporter;
}

export async function sendEmail({ to, subject, text, html, attachments }) {
  const tx = getTransporter();
  if (!tx) {
    console.warn("[email] Skipped (no SMTP config): " + subject);
    return false;
  }
  try {
    const info = await tx.sendMail({ from, to, subject, text, html, attachments });
    console.log("[email] Sent: " + subject + " to " + to + " (" + info.messageId + ")");
    return true;
  } catch (error) {
    console.error("[email] Failed to send: " + error.message);
    return false;
  }
}

function esc(str) {
  return String(str ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

export async function sendCareerApplicationEmail(payload) {
  const subject = "New Career Application - " + payload.name + " (" + payload.position + ")";

  const textLines = [
    "A new career application has been submitted via the Plumtek website.",
    "",
    "Applicant Name : " + payload.name,
    "Email          : " + payload.email,
    "Phone          : " + (payload.phone || "N/A"),
    "Position       : " + (payload.position || "N/A"),
    "Experience     : " + (payload.experience || "N/A"),
    "",
    "--- Cover Letter ---",
    payload.coverLetter || "(no cover letter provided)",
  ];

  var h = function(s) { return esc(s); };
  var html = [
    '<!DOCTYPE html><html><head><meta charset="utf-8"></head>',
    '<body style="font-family:sans-serif;color:#333;padding:24px;">',
    '<div style="max-width:640px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:8px;">',
    '<h1 style="color:#1e40af;font-size:20px;margin-top:0;">New Career Application</h1>',
    '<p>A new career application has been submitted.</p>',
    '<table style="border-collapse:collapse;width:100%;margin:16px 0;">',
    '<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;color:#475569;width:140px;">Name</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#1e293b;">' + h(payload.name) + '</td></tr>',
    '<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;color:#475569;">Email</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#1e293b;">' + h(payload.email) + '</td></tr>',
    '<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;color:#475569;">Phone</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#1e293b;">' + h(payload.phone || "N/A") + '</td></tr>',
    '<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;color:#475569;">Position</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#1e293b;">' + h(payload.position || "N/A") + '</td></tr>',
    '<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-weight:600;color:#475569;">Experience</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;color:#1e293b;">' + h(payload.experience || "N/A") + '</td></tr>',
    '</table>',
    '<p><strong>Cover Letter:</strong></p>',
    '<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:16px;margin:16px 0;white-space:pre-wrap;font-size:14px;">' + (h(payload.coverLetter).replace(/\n/g, "<br>") || "(no cover letter provided)") + '</div>',
    '<div style="font-size:12px;color:#94a3b8;margin-top:24px;">This email was automatically generated by the Plumtek Careers portal.</div>',
    '</div></body></html>',
  ].join("\n");

  return sendEmail({ to: hrEmail, subject, text: textLines.join("\n"), html });
}

export function getEmailConfig() {
  return {
    host: config.host,
    port: config.port,
    secure: config.secure,
    from,
    hrEmail,
    configured: !!(config.host && config.auth.user && config.auth.pass),
  };
}
